=== dramekhoyane-oss/XML-Projets/CabinetInfermier/cabinet.xsd
<?xml version="1.0" encoding="utf-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.univ-grenoble-alpes.fr/l3miage/medical"
        xmlns:cab="http://www.univ-grenoble-alpes.fr/l3miage/medical"
        elementFormDefault="qualified"
>
    
    <element name="cabinet" type ="cab:Cabinet">
    <!-- UNICITÉ DES ID INFIRMIERS DÉFINIE ICI (comme le prof a demandé) -->
        <unique name="uniqueIdInfirmier">
            <selector xpath=".//cab:infirmier"/>   <!-- tous les infirmiers du document -->
            <field xpath="cab:id"/>                <!-- leur id doit être unique -->
        </unique>
    </element>
    
    <!--Type Cabinet 
        contient un nom : Nom
                    prénom : Prénom 
                    infirmiers : liste Infirmier 
                    patients : Patient [0-n]
     -->
    <complexType name="Cabinet">
        <sequence>
            <element name = "nom" type="cab:NomGénérique" minOccurs="1"/>
            <element name="infirmiers" type="cab:Infirmiers" minOccurs="1"/>
            <element name ="patients" type = "cab:Patients" minOccurs="0"/> <!-- un cabinet peut ne pas avoir des patients -->
        </sequence>
    </complexType>
    
    <!--  Une classe infirmiers qui contient une liste d'infirmier -->
    
    <complexType name="Infirmiers">
        <sequence>
            <element name="infirmier" type="cab:Infirmier" minOccurs="1" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    
    <!--  une classe Patients qui contient une liste de patrint -->
    <complexType name="Patients">
        <sequence>
            <element name="patient" type="cab:Patient" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
    </complexType>
    
    <!-- type NomGénérique
        un String qui commence par une majuscule
         il sera utilisé pour nom,prénom et ville
    -->
    <simpleType name="NomGénérique">
        <restriction base="string">
            <pattern value="[A-ZÉÈÊËÀÂÎÏÔÙÜÇ][a-zA-ZéèêëàâîïôùüçÉÈÊËÀÂÎÏÔÙÜÇ]*"/>   <!-- utilisation IA pour avoir toute les lettres necessaire(unicode y compris accentuée)  -->
        </restriction>
    </simpleType>
    
    <!-- type Infirmier
        contient id : Identifiant 
                 nom : NomGénérique
                 prémon : NomGénérique 
                 photo : Photo "optionnel"  
    -->
    <complexType name="Infirmier">
        <sequence>
            <element name="id" type="cab:Identifiant" minOccurs="1"/> <!--!UNIQUE-->
            <element name="nom" type="cab:NomGénérique" minOccurs="1"/>
            <element name="prénom" type="cab:NomGénérique" minOccurs="1"/>
            <element name="photo" type="cab:Photo" minOccurs="0"/> <!--!OPTIONNELLE-->
        </sequence>
    </complexType>
    
    
    <!-- Type Patient contient 
                nom : NomGénérique
                prenom : NomGénérique
                sexe : Sexe 
                dateNaissance : date 
                numero : numSecu
                adresse : Adresse
                visite : Visite-->
    <complexType name="Patient">
        <sequence>
            <element name="nom" type="cab:NomGénérique" minOccurs="1"/>
            <element name="prénom" type="cab:NomGénérique" minOccurs="1"/>
            <element name="sexe" type="cab:Sexe" minOccurs="1"/>
            <element name="dateNaissance" type="date" minOccurs="1"/>
            <element name="numero" type="cab:numSecu" minOccurs="1"/>
            <element name="adresse" type="cab:Adresse" minOccurs="1"/>
            <element name="visite" type="cab:Visite" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    
    
    
    
    <!--simple type Identifiant
    un entier positif de trois chiffre unique (001, 999, 125...)
    utilisation de (\d -> digit ou chiffre)
    -->
    <simpleType name="Identifiant"> 
        <restriction base="integer">
            <pattern value="\d{3}"/>
        </restriction>
    </simpleType>
    
    
    
    <simpleType name="Photo">
        <restriction base ="string">
            <pattern value=".*\.(jpg|png)"/>
        </restriction>
    </simpleType>
    
    <complexType name="Visite">
        <sequence>
            <element name="acte" type="cab:Acte"/>
        </sequence>
        <attribute name="date" type="date"/>
        <attribute name="intervenant" type="cab:Identifiant"/> <!-- unique -->
    </complexType>
    
    
    
    <!-- element parent (qui contient plusieur visites) pour les  visite afin d'avoir l'unisite des intervenants  -->
    <element name="Visites">
        <complexType>
        <sequence>
            <element name="visite" type="cab:Visite" maxOccurs="unbounded"/>
        </sequence>
        </complexType>
    
        <!--unicité des intervenant -->
        <unique name="IntervenantUnique">
                <selector xpath="visite"/>
                <field xpath=" @intervenant"/>
    
        </unique>
    </element>


    <!-- -->
    <complexType name="Adresse">
        <sequence>
            <element name="etage" type="cab:NombreEntier" minOccurs="0"/>
            <element name="numero" type="cab:NombreEntier" minOccurs="0"/>
            <element name="rue" type="string" minOccurs="1"/>
            <element name="ville" type="cab:NomGénérique" minOccurs="1"/>
            <element name="codePostal" type="cab:NombreEntier" minOccurs="1"/>
        </sequence>
        
    </complexType>
    
    
    <!-- Type sexe soit F=< femme ou M => homme -->
    <simpleType name="Sexe">
        <restriction base="string">
        <pattern value="M"/>
        <pattern value="F"/>
        </restriction>
        
    </simpleType>
    
    <!-- numSecu: composé de 13 chiffres, suivi d’une clé de contrôle
            de 2 chiffres  comprise entre 01 et 97 
            0[1-9] -> 01 à 09
            [1-8][0-9]  -> 10 à 89 
            9[0-7]   -> 90 à 97
 
 -->
    <simpleType name="numSecu">
        <restriction base="string">
            <pattern value="\d{13}(0[1-9]|[1-8][0-9]|9[0-7])"/>
        </restriction>
    </simpleType>
    
    
    <complexType name="Acte">
        <attribute name="id" type="cab:Identifiant" />
        <attribute name="intitule" type="string"/>
        <attribute name="lettreCle" type="cab:LettreCle"/>
    </complexType>
    
    
    
    <!-- NombreEntier: nombre entier >=0 -->
    <simpleType name="NombreEntier">
        <restriction base="integer">
            <minInclusive value="0"/>
        </restriction>
    </simpleType>
    
    <!-- LettreCle: ensemble de 3 lettres parmi les suivantes:
            AMI pour (Acte Médico-Infirmier)
            AIS (Acte de Soins Infirmier)
            DI (Démarche de soins Infirmiers)-->
    <simpleType name="LettreCle">
        <restriction base="string">
            <pattern value="AMI"/>
            <pattern value="AIS"/>
            <pattern value="DI"/>
        </restriction>
        
    </simpleType>
    
    
</schema>

=== dramekhoyane-oss/XML-Projets/CabinetInfermier/cabinet.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="cabinet.xslt"?>
<cab:cabinet xmlns:cab = "http://www.univ-grenoble-alpes.fr/l3miage/medical"
             xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation = "http://www.univ-grenoble-alpes.fr/l3miage/medical cabinet.xsd">

    <cab:nom>LeCabinet</cab:nom>
    <cab:infirmiers>
        <cab:infirmier>
            <cab:id>999</cab:id>
            <cab:nom>Blanc</cab:nom>
            <cab:prénom>Salou</cab:prénom>
            <cab:photo>photo.png</cab:photo>
        </cab:infirmier>

        <cab:infirmier>
            <cab:id>111</cab:id>
            <cab:nom>Salla</cab:nom>
            <cab:prénom>Yacine</cab:prénom>
            <cab:photo>photo.jpg</cab:photo>
        </cab:infirmier>
    </cab:infirmiers>
    <cab:patients>
        <cab:patient>
            <cab:nom>Doria</cab:nom>
            <cab:prénom>Paul</cab:prénom>
            <cab:sexe>M</cab:sexe>
            <cab:dateNaissance>2000-05-01</cab:dateNaissance>
            <cab:numero>387340082366496</cab:numero>
            <cab:adresse >
                <cab:etage>3</cab:etage>
                <cab:numero>12</cab:numero>
                <cab:rue> Avenue Jean Loue</cab:rue>
                <cab:ville>SaintLouis</cab:ville>
                <cab:codePostal>22100</cab:codePostal>
                
            </cab:adresse>
            <cab:visite date="2024-11-22" intervenant="194" >
                <cab:acte id="109" intitule="Prelevement sanguin" lettreCle="AMI"/>
            </cab:visite >
        </cab:patient>


        <cab:patient>
            <cab:nom>Poiro</cab:nom>
            <cab:prénom>Salma</cab:prénom>
            <cab:sexe>F</cab:sexe>
            <cab:dateNaissance>2002-09-10</cab:dateNaissance>
            <cab:numero>387340082366478</cab:numero>
            <cab:adresse>
                <cab:etage>2</cab:etage>
                <cab:numero>12</cab:numero>
                <cab:rue> Rue Fievre</cab:rue>
                <cab:ville>Lille</cab:ville>
                <cab:codePostal>33100</cab:codePostal>
                
            </cab:adresse>
            <cab:visite date="2025-05-20" intervenant="999" >
                <cab:acte id="005" intitule="bactériologiques " lettreCle="AMI"/>
            </cab:visite >
        </cab:patient>


        <cab:patient>
            <cab:nom>Orouge</cab:nom>
            <cab:prénom>Elvire</cab:prénom>
            <cab:sexe>F</cab:sexe>
            <cab:dateNaissance>1982-03-08</cab:dateNaissance>
            <cab:numero>387340082366452</cab:numero>  <!-- 52e naissance? -->
            <cab:adresse >
                <cab:numero>12</cab:numero>
                <cab:rue> Rue Rond-Point de la Croix de Vie</cab:rue>
                <cab:ville>Tronche</cab:ville>
                <cab:codePostal>38700</cab:codePostal>
                
            </cab:adresse>
            <cab:visite date="2015-12-08">
                <cab:acte id="106" intitule="Pansement de brûlure étendue" lettreCle="AMI"/>
            </cab:visite >
        </cab:patient>


        <cab:patient>
            <cab:nom>Pien</cab:nom>
            <cab:prénom>Oscare</cab:prénom>
            <cab:sexe>M</cab:sexe>
            <cab:dateNaissance>1975-03-25</cab:dateNaissance>
            <cab:numero>387340082366465</cab:numero>   <!-- 692e naissance? -->
            <cab:adresse>
                <cab:numero>12</cab:numero>
                <cab:rue> Rue Casimir Brenier</cab:rue>
                <cab:ville>Grenoble</cab:ville>
                <cab:codePostal>38000</cab:codePostal>
                
            </cab:adresse>
            <cab:visite date="2015-12-08"  >
                <cab:acte intitule="Prélèvement par ponction veineuse directe, injection intraveineuse directe isolée d’anthalgiques" lettreCle="AMI"/>
            </cab:visite >
        </cab:patient>


        <cab:patient>
            <cab:nom>Kapoëtla</cab:nom>
            <cab:prénom>Xavier</cab:prénom>
            <cab:sexe>M</cab:sexe>
            <cab:dateNaissance>2011-08-02</cab:dateNaissance>
            <cab:numero>387340082366435</cab:numero>   <!-- 35e naissance? -->
            <cab:adresse>
                <cab:numero>25</cab:numero>
                <cab:rue> Rue Martyrs "</cab:rue>
                <cab:ville>Grenoble</cab:ville>
                <cab:codePostal>38042</cab:codePostal>
                
            </cab:adresse>
            <cab:visite date="2015-12-08"  >
                <cab:acte intitule="injection de plusieurs allergènes" lettreCle="AMI"/>
            </cab:visite >
        </cab:patient>
    </cab:patients>
</cab:cabinet>
